### ISSUE TITLE
Is it possible to feed an image selection into Apply Controlnet (advanced)?

### ISSUE THREAD

**Issue by cathodeDreams** [SLAPaper/ComfyUI-Image-Selector#1]
I am attempting to do a batch initial gen and use latent and image selectors to send a selection to be upscaled using controlnet tile. Attempting to send a list of image selections to controlnet results in an error:

Error occurred when executing ControlNetApplyAdvanced:

'list' object has no attribute 'movedim'

On the surface this doesn't feel like it should be possible. If there is a way I would like to know it. Thank you for any support and I apologize for my lack of technical knowledge.

**Comment by SLAPaper** [comment]
Fixed by https://github.com/SLAPaper/ComfyUI-Image-Selector/commit/4a7cf2481e250f34642f5e5424a077b0eeeb1f4e
